#!/bin/bash
pip install -r installation_support/requirements.txt
export S3X_PATH=${PWD}
echo "Environment variable S3X_PATH set to current directory $S3X_PATH."

RED='\033[0;31m'  # ANSI Red for printing critical WARNING
GREEN='\033[0;32m'  # ANSI Green for printing Important reminder
NC='\033[0m'  # ANSI No Color for ending highlighted output
CRED_FILE=data/.cred.json
CRED_EXAMPLE=installation_support/cred_EXAMPLE.json
if test -f "$CRED_FILE"; then
    echo "Credential file '$CRED_FILE' already exists."
else
    if test -f "$CRED_EXAMPLE"; then
        cp "$CRED_EXAMPLE" "$CRED_FILE"
        echo "New credential file '$CRED_FILE' created from default example '$CRED_EXAMPLE'."
    else
        printf "${RED}\nWARNING:\nNeither '%s' OR '%s' exist.\n" "$CRED_FILE" "$CRED_EXAMPLE"
        printf "Check to make sure install contents are complete.\n${NC}"
    fi
fi
printf "${GREEN}\nRefer to README for credential managament before running program.\n${NC}"

